version: '3'

volumes:
    db:
        driver: local

services:
    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
          - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: root@123
